/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 crop_top.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/crop_top.glb')
  return (
    <group {...props} dispose={null} scale={[5, 5, 5]} position={[0,-6,0]}>


{/*  front mesh  */}
      <mesh geometry={nodes.Pattern_24855.geometry} material={materials.Cotton_Canvas_FRONT_2656} />




      <mesh geometry={nodes.Pattern_24855_1.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_24855_2.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_24856.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_24856_1.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_24856_2.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_36841.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_36841_1.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_36841_2.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_117295.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_117295_1.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_117295_2.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_200678.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_200678_1.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_200678_2.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_36842.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_36842_1.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_36842_2.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_117296.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_117296_1.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_117296_2.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_200679.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_200679_1.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
      <mesh geometry={nodes.Pattern_200679_2.geometry} material={materials.Cotton_Canvas_FRONT_2656} />
    </group>
  )
}

useGLTF.preload('/crop_top.glb')
