/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 new_tshirt5.glb 
*/

import React from 'react'
import { Decal, useGLTF, useTexture } from '@react-three/drei'
import goku from './7.png'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/new_tshirt5.glb')
  const texture = useTexture(goku)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.T_Shirt_Front.geometry} material={materials.Front_Shader_1} />
      <mesh geometry={nodes.T_Shirt_Back.geometry} material={materials.Back_Shader_2} />
      <mesh geometry={nodes.T_Shirt_Decal_Front1.geometry} material={materials.Decal_shader} position={[0, 0, 0.001]} />
      <mesh geometry={nodes.pCylinder1.geometry} material={materials.R_Sleeve_Shader_Yellow} position={[0.29, 0.014, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.051} />
      <mesh geometry={nodes.pCylinder2.geometry} material={materials.L_Sleeve_Shader_Pink} position={[-0.3, 0.02, -0.009]} rotation={[Math.PI / 2, 0, 3.081]} scale={0.051} />
      <mesh geometry={nodes.pCylinder3.geometry} material={materials.R_decal_mesh_text} position={[0.221, 0.099, -0.017]} rotation={[Math.PI / 2, 0.286, -0.022]} scale={[0.033, 0.033, 0.042]} >
      
      <Decal  position={[-0.9,0.2,-1.7]}  rotation={[-1.7,1,0]} scale={[3, 3, 3]} map={texture} />
      
      </mesh>
      <mesh geometry={nodes.polySurface1.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface10.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface11.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface12.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface13.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface14.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface15.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface16.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface17.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface18.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface19.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface2.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface20.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface21.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface22.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface23.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface24.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface25.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface26.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface27.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface3.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface4.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface6.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface7.geometry} material={materials.lambert2} />
      <mesh geometry={nodes.polySurface9.geometry} material={materials.lambert2} />
    </group>
  )
}

useGLTF.preload('/new_tshirt5.glb')
